# create as many configuration files as you want

client:
  process_names:                                                       # List of process names to monitor
    - "com.familyzone.macappproxy.fzmacdnsproxy"
    - "com.familyzone.macappproxy.fzmacappproxy"
  # log_file_postfix: "v3.6.9-1291-prd-MITM_ON-WEB"
  log_file_postfix: "v3.6.9-1291-prd-MITM_ON-WEB"                     # a string to append to the CSV file names
  # log_file_postfix: "unfiltered"
  server_host: "server"
  server_udp_port: 9000
  server_ping_port: 9001
  server_tcp_http_port: 80
  server_tcp_https_port: 443
  server_udp_dns_port: 53
  server_tcp_dns_port: 53
  tests:
    idle_state_of_device: 
      enable: true
    idle_state_of_process:
      enable: true
    http_throughput:
      enable: true
    https_throughput:
      enable: false
    ping:
      enable: true
      countSamples: 100
    jitter:
      enable: true
      countDifferences: 100
    http_burst:
      enable: true
    https_burst:
      enable: false
    http_rate:
      enable: true
      duration: 10
    https_rate:
      enable: false
      duration: 10
    dns_udp_burst:
      enable: true
    dns_tcp_burst:
      enable: false
    dns_udp_rate:
      enable: true
      duration: 10
    dns_tcp_rate:
      enable: false
      duration: 10
